_wandb:
    value:
        cli_version: 0.21.0
        e:
            tgukar6c01zp7vehpzxk9a5ptreo41wc:
                args:
                    - --mode
                    - train
                    - --use_wandb
                codePath: scripts\training.py
                codePathLocal: scripts\training.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "999507046400"
                        used: "245634961408"
                email: aochen@bu.edu
                executable: C:\Users\aochen\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: d96569429d383d18a064a0e82599550858291495
                    remote: https://github.com/aochen0525/AEC_DL.git
                gpu: Quadro RTX 4000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2304
                      memoryTotal: "8589934592"
                      name: Quadro RTX 4000
                      uuid: GPU-d5d2044e-1d2d-a069-ffae-342fa33dc335
                host: ROG
                memory:
                    total: "137347371008"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\aochen\Desktop\Acoustic_DL\AEC_DL\scripts\training.py
                python: CPython 3.10.10
                root: C:\Users\aochen\Desktop\Acoustic_DL\AEC_DL
                startedAt: "2025-07-05T19:00:56.739198Z"
                writerId: tgukar6c01zp7vehpzxk9a5ptreo41wc
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.10.10
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 2
epochs:
    value: 20
hidden_dim:
    value: 512
learning_rate:
    value: 0.0001
model_type:
    value: transformer
num_layers:
    value: 6
